### ISSUE TITLE
dhcpd-pools: parse_config: /etc/dhcp/dhcpd.conf: No such file or directory

### ISSUE THREAD

**Issue by MarkusEckerl** [djaydev/docker-glass-isc-dhcp#4] opened 2020-10-27 12:54 UTC
Started with:
docker run -d \
    --name=glass-isc-dhcp \
    --network="host" \
    -e TZ=Europe/Berlin \
    -v /docker/appdata/glass-isc-dhcp:/etc/dhcp:rw \
    -v /docker/appdata/glass-isc-dhcp/leases:/var/lib/dhcp:rw \
    -e ADMINPASSWORD=xxxxxxx \
    -e WEBSOCKETPORT=8080 \
    -e WEBADMINPORT=3000 \
    djaydev/glass-isc-dhcp

dhcpd.conf on host in /etc/dhcpd is:

authoritative;

default-lease-time 7200;
max-lease-time 7200;

subnet 192.168.0.0 netmask 255.255.255.0 {
	option routers 192.168.0.1;
	option subnet-mask 255.255.255.0;
	range 192.168.0.10 192.168.0.254;
	option broadcast-address 192.168.0.255;
	option domain-name-servers 1.1.1.1, 9.9.9.9;
	option domain-name "local.example.com";
	option domain-search "local.example.com";
}

after a few seconds I get:
dhcpd-pools: parse_config: /etc/dhcp/dhcpd.conf: No such file or directory

**Comment by djaydev** [comment] 2020-10-27 13:10
Hi @MarkusEckerl !
Hope you enjoy the docker :) lets see if we can get it going for you.

You are receiving this error because the file "dhcpd.conf" is not readable by the docker container.  It has to be available in the folder /etc/dhcp/ .

The first thing I would do is start with the host machine, from the CLI type:
` ls -lah /docker/appdata/glass-isc-dhcp `
Here I'd be looking to make sure there's a file named dhcpd.conf, as well as checking the permissions of the file to make sure it has at least read permissions.

After that, you can do the same thing inside the container, but the path will be different of course:
 ```
docker run -ti \
--name=glass-isc-dhcp  \
--network="host" \
-e TZ=Europe/Berlin \
-v /docker/appdata/glass-isc-dhcp:/etc/dhcp:rw \
-v /docker/appdata/glass-isc-dhcp/leases:/var/lib/dhcp:rw \
--entrypoint='bash' \
djaydev/glass-isc-dhcp
```
Here let's check for the same file, but from the containers perspective:
`ls -lah  /etc/dhcp/ `
Here I'd be looking to make sure there's a file named dhcpd.conf, as well as checking the permissions of the file to make sure it has at least read permissions.

Somewhere between those steps is where the problem is.  I'll help as much as I can but the problem is going to be unique to your host/OS/file system/docker version/etc.

**Comment by MarkusEckerl** [comment] 2020-10-27 16:42
Hi!
Thank you very much for your fast reply.
I tried the things you suggested.

Now I know that a "|ls -lah /docker/appdata/glass-isc-dhcp" doesn't show
me the expected "||dhcpd.conf". So it is clear to me why the docker
image want work as expected.|

|This is a bit curious for me because the file is of course in the
/etc/dhcp directory and the docker image is definitely started with the
correct syntax.
|

|root@cont:~# ls -alh /etc/dhcp/
total 28K
drwxr-xr-x   6 root root  161 Oct 27 12:56 .
drwxr-xr-x 105 root root 8.0K Oct 27 10:00 ..
-rw-r--r--   1 root root 1.4K Nov 18  2018 debug
-rw-r--r--   1 root root 1.7K Nov 18  2018 dhclient.conf
drwxr-xr-x   2 root root   19 Oct  6 16:00 dhclient-enter-hooks.d
drwxr-xr-x   2 root root   79 Oct  6 20:01 dhclient-exit-hooks.d
-rw-r--r--   1 root root 3.3K Dec 11  2018 dhcpd6.conf
-rw-r--r--   1 root root 3.2K Oct 27 12:56 dhcpd.conf
drwxr-xr-x   3 root root   18 Oct 27 12:07 etc
drwxr-xr-x   2 root root    6 Oct 27 10:27 leases
|


Then I tried to start with:

docker run -ti \
--name=glass-isc-dhcp  \
--network="host" \
-e TZ=Europe/Berlin \
-v /docker/appdata/glass-isc-dhcp:/etc/dhcp:rw \
-v /docker/appdata/glass-isc-dhcp/leases:/var/lib/dhcp:rw \
--entrypoint='bash' \
djaydev/glass-isc-dhcp

did a ||"ls -lah /etc/dhcp/" and surpise, like expected no "dhcpd.conf".
||

|OS is Debian 10. Docker is docker ce from https://download.docker.com/:|

|
|

|Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:25 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
|

|
|


|What can / should I try now?|

|
|

||

**Comment by djaydev** [comment] 2020-10-27 16:53
I think I may see the confusion here.  
When you run docker with " -v " you are mapping a host directory to a directory inside the container.  The first half is the folder on your host, the second part is the folder that will be seen inside the docker container.

`-v /docker/appdata/glass-isc-dhcp:/etc/dhcp:rw \`
So that line means to connect the folder "/docker/appdata/glass-isc-dhcp" on the host to "/etc/dhcp" inside the docker container. If your dhcpd.conf file is not located in "/docker/appdata/glass-isc-dhcp" it won't work inside the docker container.

What it looks like you want is this:
```
-v /etc/dhcp/:/etc/dhcp:rw \
-v /etc/dhcp/leases:/var/lib/dhcp/leases:rw \

**Comment by MarkusEckerl** [comment] 2020-10-27 16:58
Indeed. :(
stupid mistake. Maybe I should learn to read ;)
Thanks a lot for your help. Now it is working like a charm!

**Comment by djaydev** [comment] 2020-10-27 16:59
No problem! Enjoy!
Closing since it's now resolved.

**Closed by djaydev** 2020-10-27 16:59 UTC
